Repository nextcloud-libraries/nextcloud-initial-state, pull requests merged in 2023-06, with the labels that each got.

#537 chore: update workflows from templates
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies, automated, 3. to review

#348 Update npm and node engines versions
  package.json
Labels: dependencies

#543 Fix package exports
  package.json
Labels: 3. to review

#544 chore: update node engines to next LTS
  .github/workflows/node-test.yml
  package.json
Labels: dependencies, automated, 3. to review
